# Generated by Django 3.1.7 on 2021-04-06 01:16

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Airframe Name', max_length=200)),
                ('stations', models.IntegerField(default=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The Campaign Name.', max_length=200)),
                ('description', models.TextField(default='Campaign description to be added here.', help_text='A brief description used for display purposes on selection screens.')),
                ('start_date', models.DateField(blank=True, help_text='Proposed Start Date of Campaign.', null=True, verbose_name='Expected Start Date')),
                ('campaignImage', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Campaign Image File.', keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='campaign/thumbnails/', verbose_name='Campaign Image File.')),
                ('created_by', models.CharField(blank=True, help_text='Name of campaign creator.', max_length=200, null=True)),
                ('situation', models.TextField(blank=True, help_text='A detailed overview of the background and situation for the campaign.', null=True)),
                ('aoImage', models.ImageField(blank=True, help_text='An image of the Area of Operations.', null=True, upload_to='campaign/ao_images/', verbose_name='area of Operations Image')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, help_text='A number representing the mission order within the campaign.', verbose_name='mission number')),
                ('name', models.CharField(help_text='Enter Mission Name', max_length=200)),
                ('description', models.TextField(default='Mission description to be added here.', help_text='Enter Mission Description/Situation.')),
                ('brief', models.TextField(blank=True, help_text='Enter Detailed Mission Brief.', null=True, verbose_name='Tactical Mission Brief')),
                ('roe', models.TextField(blank=True, help_text='Enter Rules of Engagement', null=True, verbose_name='Rules of Engagement')),
                ('munitions_restrictions', models.TextField(blank=True, help_text='Enter any restrictions on use of munitions/weaponry.', null=True, verbose_name='munitions restrictions')),
                ('mission_time', models.CharField(blank=True, help_text='Mission time in HH:MM format.', max_length=5, null=True, verbose_name='mission Start Time')),
                ('mission_date', models.DateField(blank=True, help_text='Proposed mission date.', null=True, verbose_name='expected Mission Date')),
                ('cloud_base', models.CharField(blank=True, help_text='Enter Cloud base in K of ft.', max_length=10, null=True, verbose_name='Cloud Base Altitude')),
                ('cloud_top', models.CharField(blank=True, help_text='Enter Cloud Tops in K of ft.', max_length=10, null=True, verbose_name='Cloud Tops')),
                ('wind_sl', models.CharField(blank=True, help_text='Enter Wind at Sea Level', max_length=20, null=True, verbose_name='Wind at Sea Level')),
                ('wind_7k', models.CharField(blank=True, help_text='Enter Wind at 7K ft.', max_length=20, null=True, verbose_name='Wind at 7K ft')),
                ('wind_26k', models.CharField(blank=True, help_text='Enter Wind at 26K ft.', max_length=20, null=True, verbose_name='Wind at 26K ft')),
                ('qnh', models.CharField(blank=True, help_text='Enter QNH', max_length=20, null=True, verbose_name='QNH')),
                ('qfe', models.CharField(blank=True, help_text='Enter QFE', max_length=20, null=True, verbose_name='QFE')),
                ('temp', models.CharField(blank=True, help_text='Enter temperature in C.', max_length=20, null=True, verbose_name='Temperature in Celcius')),
                ('sigwx', models.CharField(blank=True, help_text='SIGWX', max_length=20, null=True, verbose_name='SIGWX')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.campaign')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Status Type', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Terrain Map Name.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('threat_type', models.CharField(choices=[('AAA', 'AAA'), ('SAM', 'SAM'), ('AIR', 'AIR'), ('NAVAL', 'NAVAL'), ('GROUND', 'GROUND')], max_length=10, null=True)),
                ('description', models.TextField(default='Threat description to be added here.', help_text='Enter Threat Description/Situation.')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Package Name', max_length=200, verbose_name='Package Name')),
                ('description', models.TextField(blank=True, help_text='Enter Mission Description/Situation.', null=True, verbose_name='Description of package objective')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.mission')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(help_text='Enter Flight Callsign', max_length=200)),
                ('radio_frequency', models.CharField(blank=True, help_text='Enter Flight Frequency', max_length=20, null=True)),
                ('tacan', models.CharField(blank=True, help_text='Enter Flight TACAN (if applicable)', max_length=5, null=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.package')),
            ],
            options={
                'ordering': ['callsign'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='dcs_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.terrain', verbose_name='dcs Terrain'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.status'),
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.CharField(blank=True, help_text='Enter Pilot Name', max_length=30, null=True)),
                ('rio_wso', models.CharField(blank=True, help_text='Enter RIO/WSO Name', max_length=30, null=True)),
                ('tailcode', models.CharField(blank=True, help_text='Enter A/C tail code.', max_length=20, null=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.flight')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.airframe')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
