# Generated by Django 3.1.7 on 2021-04-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter target name', max_length=50, verbose_name='Target Name')),
                ('lat', models.CharField(help_text='Enter target latitude', max_length=200, verbose_name='Target Latitude')),
                ('long', models.CharField(help_text='Enter target longitude.', max_length=200, verbose_name='Target Longitude')),
                ('elev', models.CharField(help_text='Enter target elevation.', max_length=200, verbose_name='Target Elevation')),
                ('notes', models.TextField(blank=True, help_text='Any notes relevant to the target.', null=True, verbose_name='Notes on Target')),
                ('target_image', models.ImageField(blank=True, help_text='Upload image of the target.', null=True, upload_to='campaign/mission/target_images/', verbose_name='Target Image')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.mission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
