# Generated by Django 3.1.7 on 2021-04-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0002_auto_20210408_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_game_date',
            field=models.DateField(blank=True, help_text='Mission game date.', null=True, verbose_name='In-Game Mission Date'),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_game_time',
            field=models.CharField(blank=True, help_text='Mission game start time in HH:MM format.', max_length=5, null=True, verbose_name='In-Game Mission Start Time'),
        ),
        migrations.AddField(
            model_name='mission',
            name='visibility',
            field=models.CharField(blank=True, help_text='Enter Visibility.', max_length=10, null=True, verbose_name='Visibility'),
        ),
        migrations.AddField(
            model_name='package',
            name='frequency',
            field=models.CharField(blank=True, help_text='Enter Package Frequency', max_length=10, null=True, verbose_name='Package Frequency'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='targets',
            field=models.ManyToManyField(blank=True, to='airops.Target'),
        ),
    ]
