# Generated by Django 3.1.7 on 2021-04-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0003_auto_20210411_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='visibility',
            field=models.CharField(blank=True, help_text='Enter Visibility.', max_length=100, null=True, verbose_name='Visibility'),
        ),
    ]
