# Generated by Django 3.1.7 on 2021-04-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0004_auto_20210411_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='flight_lead',
            field=models.BooleanField(default=False),
        ),
    ]
