# Generated by Django 3.1.7 on 2021-03-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0004_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(help_text='Enter Campaign Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(help_text='Start Date of Campaign'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(help_text='Enter Mission Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(help_text='Enter Package Name', max_length=200),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(help_text='Enter Flight Callsign', max_length=200)),
                ('radio_frequency', models.CharField(help_text='Enter Flight Frequency', max_length=20)),
                ('tacan', models.CharField(help_text='Enter Flight TACAN (if applicable)', max_length=5)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airops.package')),
            ],
            options={
                'ordering': ['-callsign'],
            },
        ),
    ]
