# Generated by Django 3.1.7 on 2021-04-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0004_flighttarget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightTarget',
        ),
    ]
