# Generated by Django 3.2 on 2021-04-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0005_aircraft_flight_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter notes for the waypoint.', null=True),
        ),
    ]
