# Generated by Django 3.1.7 on 2021-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0005_delete_flighttarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='targets',
            field=models.ManyToManyField(to='airops.Target'),
        ),
    ]
