# Generated by Django 3.1.7 on 2021-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0006_auto_20210317_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='Campaign Description', help_text='Enter Campaign Description/Situation.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(help_text='Enter Campaign Name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(help_text='Date Campaign Ended.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(help_text='Start Date of Campaign.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(help_text='Enter Current Status of Campaign.', max_length=200),
        ),
    ]
