# Generated by Django 2.2.10 on 2021-04-25 01:01

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0006_alter_waypoint_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='package_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Campaign Image File.', keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='campaign/thumbnails/', verbose_name='Campaign Image Thumbnail.'),
        ),
    ]
