# Generated by Django 3.1.7 on 2021-04-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0006_flight_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=50)),
                ('support_type', models.CharField(choices=[('AWACS', 'AWACS'), ('TANKER', 'TANKER'), ('JTAC', 'JTAC'), ('CARRIER', 'CARRIER')], max_length=10, null=True)),
                ('frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('tacan', models.CharField(blank=True, max_length=10, null=True)),
                ('altitude', models.CharField(blank=True, max_length=10, null=True)),
                ('speed', models.CharField(blank=True, max_length=10, null=True)),
                ('brc', models.CharField(blank=True, max_length=10, null=True)),
                ('icls', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Enter notes for support resource.', null=True)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.mission')),
            ],
        ),
    ]
