# Generated by Django 3.1.7 on 2021-03-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0007_auto_20210322_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Status Type', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='mission_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='mission_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(default='Test Desc', help_text='Enter Mission Description/Situation.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airops.status'),
        ),
    ]
