# Generated by Django 3.1.7 on 2021-04-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0007_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='fuel_bingo',
            field=models.CharField(blank=True, help_text='Fuel BINGO.', max_length=10, null=True, verbose_name='Fuel BINGO'),
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_fob',
            field=models.CharField(blank=True, help_text='Fuel FOB', max_length=10, null=True, verbose_name='Fuel FOB'),
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_joker',
            field=models.CharField(blank=True, help_text='Fuel JOKER.', max_length=10, null=True, verbose_name='Fuel JOKER'),
        ),
        migrations.AddField(
            model_name='flight',
            name='timehack_rdv1',
            field=models.CharField(blank=True, help_text='Enter time for flight rendevous point 1.', max_length=10, null=True, verbose_name='Time RDV 1'),
        ),
        migrations.AddField(
            model_name='flight',
            name='timehack_rdv2',
            field=models.CharField(blank=True, help_text='Enter time for flight rendevous point 2.', max_length=10, null=True, verbose_name='Time RDV 2'),
        ),
        migrations.AddField(
            model_name='flight',
            name='timehack_start',
            field=models.CharField(blank=True, help_text='Enter time for flight takeoff.', max_length=10, null=True, verbose_name='Takeoff Time'),
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=1, help_text='A number representing the waypoint order.', verbose_name='waypoint number')),
                ('waypoint_type', models.CharField(choices=[('NAV', 'NAV'), ('IP', 'IP'), ('CAP', 'CAP'), ('STRIKE', 'STRIKE'), ('CAS', 'CAS'), ('DEAD', 'DEAD'), ('SEAD', 'SEAD'), ('BAI', 'BAI'), ('TAKEOFF', 'TAKEOFF'), ('LAND', 'LAND'), ('DIVERT', 'DIVERT')], max_length=10, null=True)),
                ('lat', models.CharField(blank=True, max_length=15, null=True)),
                ('long', models.CharField(blank=True, max_length=15, null=True)),
                ('elevation', models.CharField(blank=True, max_length=15, null=True)),
                ('tot', models.CharField(blank=True, max_length=15, null=True, verbose_name='time on Target')),
                ('notes', models.TextField(blank=True, help_text='Enter notes for support resource.', null=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.flight')),
            ],
        ),
    ]
