# Generated by Django 3.1.7 on 2021-03-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0008_auto_20210322_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date Campaign Ended.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start Date of Campaign.', null=True),
        ),
    ]
