# Generated by Django 2.2.10 on 2021-04-25 04:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0008_auto_20210425_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image of the target.', keep_meta=True, null=True, quality=0, size=[1500, 1200], upload_to='campaign/mission/target_images/', verbose_name='Target Image'),
        ),
    ]
