# Generated by Django 3.1.7 on 2021-03-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0009_auto_20210322_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='radio_frequency',
            field=models.CharField(blank=True, help_text='Enter Flight Frequency', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='tacan',
            field=models.CharField(blank=True, help_text='Enter Flight TACAN (if applicable)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
