# Generated by Django 3.1.7 on 2021-03-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0010_auto_20210322_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='Enter Mission Description/Situation.', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, help_text='Enter Mission Description/Situation.', null=True),
        ),
    ]
