# Generated by Django 3.1.7 on 2021-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0011_auto_20210322_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Airframe Name', max_length=200)),
                ('stations', models.IntegerField(default=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
