# Generated by Django 2.2.10 on 2021-05-17 06:47

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0012_auto_20210511_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionImagery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for mission.', keep_meta=True, null=True, quality=0, size=[1500, 1200], upload_to='campaign/mission/mission_images/', verbose_name='Mission Imagery')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.Mission')),
            ],
        ),
    ]
