# Generated by Django 3.1.7 on 2021-03-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0012_airframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airops.airframe'),
        ),
    ]
