# Generated by Django 3.1.7 on 2021-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0013_auto_20210322_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
