# Generated by Django 3.1.7 on 2021-03-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0014_mission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaignImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.campaign'),
        ),
    ]
