# Generated by Django 2.2.10 on 2021-05-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0014_campaign_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='created_by',
        ),
    ]
