# Generated by Django 2.2.10 on 2021-05-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0016_threatreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatreference',
            name='description',
        ),
        migrations.AddField(
            model_name='threatreference',
            name='acquire_time',
            field=models.IntegerField(default=0, help_text='Time to acquire (secs).'),
        ),
        migrations.AddField(
            model_name='threatreference',
            name='alt_max',
            field=models.IntegerField(default=0, help_text='Maximum engagement altitude (ft).'),
        ),
        migrations.AddField(
            model_name='threatreference',
            name='alt_min',
            field=models.IntegerField(default=0, help_text='Minimum engagement altitude (ft).'),
        ),
        migrations.AddField(
            model_name='threatreference',
            name='gun_ammo',
            field=models.IntegerField(default=0, help_text='Number of gun rounds.'),
        ),
        migrations.AddField(
            model_name='threatreference',
            name='missile_ammo',
            field=models.IntegerField(default=0, help_text='Number of missiles.'),
        ),
        migrations.AddField(
            model_name='threatreference',
            name='range_max',
            field=models.IntegerField(default=0, help_text='Maximum enagengagementement range (nmi).'),
        ),
        migrations.AddField(
            model_name='threatreference',
            name='range_min',
            field=models.IntegerField(default=0, help_text='Minimum engagement range (nmi).'),
        ),
        migrations.AddField(
            model_name='threatreference',
            name='threat_type',
            field=models.CharField(choices=[('OPTICAL', 'OPTICAL'), ('RADAR', 'RADAR'), ('LASER', 'LASER'), ('IR', 'IR')], max_length=10, null=True),
        ),
    ]
