# Generated by Django 3.1.7 on 2021-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0016_auto_20210402_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='aoImage',
            field=models.ImageField(blank=True, help_text='An image of the Area of Operations.', null=True, upload_to='images/'),
        ),
    ]
