# Generated by Django 2.2.10 on 2021-05-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0017_auto_20210529_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='threat_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.ThreatReference'),
        ),
    ]
