# Generated by Django 2.2.10 on 2021-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0018_threat_threat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatreference',
            name='acquire_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Time to acquire (secs).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='alt_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum engagement altitude (ft).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='alt_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum engagement altitude (ft).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='range_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum enagengagementement range (nmi).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='range_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum engagement range (nmi).', max_digits=8),
        ),
    ]
