# Generated by Django 3.1.7 on 2021-04-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0018_auto_20210402_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='aoImage',
            field=models.ImageField(blank=True, help_text='An image of the Area of Operations.', null=True, upload_to='images/', verbose_name='area of operations image'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dcs_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airops.terrain', verbose_name='dcs terrain'),
        ),
    ]
