# Generated by Django 3.1.7 on 2021-04-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0019_auto_20210403_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.flight'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.airframe'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dcs_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.terrain', verbose_name='dcs Terrain'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, help_text='Proposed Start Date of Campaign.', null=True, verbose_name='Expected Start Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.status'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.package'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='brief',
            field=models.TextField(blank=True, help_text='Enter Detailed Mission Brief.', null=True, verbose_name='Tactical Mission Brief'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_date',
            field=models.DateField(blank=True, help_text='Proposed mission date.', null=True, verbose_name='expected Mission Date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_time',
            field=models.CharField(blank=True, help_text='Mission time in HH:MM format.', max_length=5, null=True, verbose_name='mission Start Time'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='munitions_restrictions',
            field=models.TextField(blank=True, help_text='Enter any restrictions on use of munitions/weaponry.', null=True, verbose_name='munitions restrictions'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='number',
            field=models.IntegerField(default=1, help_text='A number representing the mission order within the campaign.', verbose_name='mission number'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='roe',
            field=models.TextField(blank=True, help_text='Enter Rules of Engagement', null=True, verbose_name='Rules of Engagement'),
        ),
        migrations.AlterField(
            model_name='package',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.mission'),
        ),
    ]
