# Generated by Django 2.2.10 on 2021-05-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0019_auto_20210529_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatreference',
            options={'ordering': ['name']},
        ),
    ]
