# Generated by Django 3.1.7 on 2021-04-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0020_auto_20210403_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(default='Description here.', help_text='Enter Mission Description/Situation.'),
            preserve_default=False,
        ),
    ]
