# Generated by Django 2.2.10 on 2021-05-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0020_auto_20210529_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatreference',
            name='harm_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
