# Generated by Django 3.1.7 on 2021-04-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0022_auto_20210403_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='aoImage',
            field=models.ImageField(blank=True, help_text='An image of the Area of Operations.', null=True, upload_to='images/', verbose_name='area of Operations Image'),
        ),
    ]
