# Generated by Django 3.1.7 on 2021-04-04 06:18

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0025_auto_20210404_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='aoImage',
            field=models.ImageField(blank=True, help_text='An image of the Area of Operations.', null=True, upload_to='campaign/ao_images/', verbose_name='area of Operations Image'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Campaign Image File.', keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='campaign/thumbnails/'),
        ),
    ]
