# Generated by Django 2.2.10 on 2021-05-29 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airops', '0025_auto_20210529_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='pilot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='pilot',
            field=models.CharField(blank=True, help_text='Enter Pilot Name', max_length=30, null=True),
        ),
    ]
