# Generated by Django 2.2.10 on 2021-05-29 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0026_auto_20210529_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='pilot2',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
