# Generated by Django 3.1.7 on 2021-04-04 11:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0026_auto_20210404_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaignImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Campaign Image File.', keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='campaign/thumbnails/', verbose_name='Campaign Image File.'),
        ),
    ]
