# Generated by Django 3.2.4 on 2021-07-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0028_auto_20210529_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['-flight_lead'], 'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Campaign Status', 'verbose_name_plural': 'Campaign Status'},
        ),
        migrations.AlterModelOptions(
            name='terrain',
            options={'verbose_name_plural': 'Terrain'},
        ),
        migrations.AlterModelOptions(
            name='threatreference',
            options={'ordering': ['name'], 'verbose_name': 'Threat Reference', 'verbose_name_plural': 'Threat References'},
        ),
        migrations.AddField(
            model_name='airframe',
            name='multicrew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_time',
            field=models.CharField(blank=True, default='20:00 AEST', help_text='Mission time in HH:MM format.', max_length=5, null=True, verbose_name='mission Start Time'),
        ),
    ]
