# Generated by Django 3.2.4 on 2021-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0029_auto_20210703_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['-flight_lead', '-pilot'], 'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.AddField(
            model_name='package',
            name='package_coordination',
            field=models.TextField(blank=True, help_text='Notes for package co-ordination.', null=True, verbose_name='Notes for package co-ordination'),
        ),
        migrations.AddField(
            model_name='package',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary of Package objective.', null=True, verbose_name='Summary of package objective'),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_type',
            field=models.CharField(choices=[('AWACS', 'AWACS'), ('TANKER', 'TANKER'), ('JTAC', 'JTAC'), ('CARRIER', 'CARRIER'), ('LHA', 'LHA'), ('ABM', 'ABM'), ('AIRFIELD', 'AIRFIELD')], max_length=10, null=True),
        ),
    ]
