# Generated by Django 3.2.4 on 2021-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0030_auto_20210710_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_coordination',
            field=models.TextField(blank=True, help_text='Use this field to enter in any notes that the flight lead might need to use to coordinate other members of the flight,', null=True, verbose_name='Notes for flight co-ordination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_coordination',
            field=models.TextField(blank=True, help_text='Use this field to enter in any notes that the package lead might need to use to coordinate other members of the package,', null=True, verbose_name='Notes for package co-ordination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='summary',
            field=models.TextField(blank=True, help_text='Use this field to describe the overall objectives for the package.', null=True, verbose_name='Summary of package objective'),
        ),
    ]
