# Generated by Django 3.2.5 on 2021-07-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('airops', '0032_auto_20210712_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('timezone', models.CharField(blank=True, max_length=256, null=True)),
                ('callsign', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
