# Generated by Django 3.2.5 on 2021-07-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0033_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_date',
            field=models.DateTimeField(blank=True, help_text='Proposed mission Date. (UTC)', null=True, verbose_name='expected Mission Date (UTC)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_game_date',
            field=models.DateTimeField(blank=True, help_text='Mission game date.', null=True, verbose_name='In-Game Mission Date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_time',
            field=models.TimeField(blank=True, default='10:00', help_text='Mission time in HH:MM format. (UTC)', max_length=5, null=True, verbose_name='mission Start Time (UTC)'),
        ),
    ]
