# Generated by Django 3.2.4 on 2021-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0037_mission_discord_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='notify_discord',
            field=models.BooleanField(default=False, verbose_name='Send Notification To Discord'),
        ),
    ]
