# Generated by Django 3.2.4 on 2021-07-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0038_mission_notify_discord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terrain',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Terrain'},
        ),
        migrations.AlterField(
            model_name='mission',
            name='notify_discord',
            field=models.BooleanField(default=False, verbose_name='Send Notification To Discord if Webhook configured.'),
        ),
    ]
