# Generated by Django 3.2.4 on 2021-07-31 04:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0039_auto_20210731_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='assets/img/avatars/pilot1.png', force_format='PNG', help_text='User profile image file.', keep_meta=True, null=True, quality=0, size=[200, 200], upload_to='user/profilepics/', verbose_name='User profile image.'),
        ),
    ]
