# Generated by Django 3.2.4 on 2021-08-01 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airops', '0041_auto_20210731_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Mission File Name', max_length=100, verbose_name='Misison File Name')),
                ('mission_file', models.FileField(null=True, upload_to='')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.mission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mission File Uploader')),
            ],
            options={
                'verbose_name': 'Mission File',
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='CombatFliteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter CombatFlite File Name', max_length=100, verbose_name='Combat Flight File Name')),
                ('combatflite_file', models.FileField(null=True, upload_to='')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.mission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CombatFlite File Uploader')),
            ],
            options={
                'verbose_name': 'Combat Flite File',
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
