# Generated by Django 3.2.4 on 2021-08-01 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airops', '0042_combatflitefile_missionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mission Creator'),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
