# Generated by Django 3.2.6 on 2021-08-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0044_auto_20210808_1802'),
        ('airops', '0044_missionfile_file_type'),
    ]

    operations = [
    ]
