# Generated by Django 3.2.6 on 2021-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0046_Add_Squadron_Table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadron',
            name='squadron_url',
            field=models.URLField(null=True, verbose_name='Squadron Website'),
        ),
    ]
