# Generated by Django 3.2.6 on 2021-08-19 03:40

from django.db import migrations


def create_squadrons(apps, schema_editor):
    squadron = apps.get_model("airops", "Squadron")
    if squadron.objects.all().count() == 0:
        sqn_none = squadron()
        sqn_none.squadron_name = "None"
        sqn_none.squadron_url = ""
        sqn_161 = squadron()
        sqn_161.squadron_name = "161 SQN"
        sqn_161.squadron_url = ""
        sqn_none.save()
        sqn_161.save()


def assign_existing_users_to_default_sqn(apps, schema_editor):
    users = apps.get_model("airops", "UserProfile")
    squadron = apps.get_model("airops", "Squadron")
    sqn_none = squadron.objects.get(pk=1)
    for user in users.objects.all():
        user.squadron = sqn_none
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("airops", "0046_create_squadron_table_and_field"),
    ]

    operations = [
        migrations.RunPython(create_squadrons, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(assign_existing_users_to_default_sqn, reverse_code=migrations.RunPython.noop),

    ]
