# Generated by Django 3.2.6 on 2021-08-17 09:10

import airops.models.UserProfile
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0047_UpdateSquadronUrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='assets/img/avatars/pilot1.png', force_format='PNG', help_text='User profile image file.', keep_meta=True, quality=0, size=[200, 200],  verbose_name='User profile image.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='squadron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.squadron', verbose_name='Squadron'),
        ),
    ]
