# Generated by Django 3.2.6 on 2021-08-19 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0047_populate_squadronss_and_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='squadron',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, to='airops.squadron',
                                    verbose_name='Squadron'),
        ),
    ]
