# Generated by Django 3.2.6 on 2021-08-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0046_auto_20210817_1230'),
        ('airops', '0048_make_squadorn_not_nullable'),
    ]

    operations = [
    ]
