# Generated by Django 3.2.6 on 2021-09-11 07:11

from apps.airops.models import Squadron
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0049_merge_20210820_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadron',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='assets/img/avatars/pilot1.png', force_format='PNG', help_text='User profile image file.', keep_meta=True, quality=0, size=[200, 200], upload_to='user/profile_images/<property object at 0x1059b28b0>/', verbose_name='User profile image.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='squadron',
            field=models.ForeignKey(default=Squadron.get_default_pk, null=True, on_delete=django.db.models.deletion.PROTECT, to='airops.squadron', verbose_name='Squadron'),
        ),
    ]
