# Generated by Django 3.2.6 on 2021-09-15 06:01

from django.db import migrations


def populate_waypoint_types(apps, schema_editor):
    values = (
        "NAV",
        "IP",
        "CAP",
        "STRIKE",
        "CAS",
        "DEAD",
        "SEAD",
        "BAI",
        "TAKEOFF",
        "LAND",
        "DIVERT",
    )
    waypoint_types_model = apps.get_model("airops", "WaypointType")
    create_entries(apps, waypoint_types_model, values)


def populate_threat_types(apps, schema_editor):
    values = (
        "AAA",
        "SAM",
        "AIR",
        "NAVAL",
        "GROUND",
    )
    threat_type_model = apps.get_model("airops", "ThreatType")
    create_entries(apps, threat_type_model, values)


def populate_support_types(apps):
    values = (
        "AWACS",
        "TANKER",
        "JTAC",
        "CARRIER",
        "LHA",
        "ABM",
        "AIRFIELD",
    )
    support_type_model = apps.get_model("airops", "SupportType")
    create_entries(apps, support_type_model, values)


def create_entries(apps, model, values):
    user_model = apps.get_model("auth", "User")
    user = user_model.objects.first()
    for value in values:
        obj, created = model.objects.get_or_create(name=value, defaults={"user": user})


class Migration(migrations.Migration):

    dependencies = [
        ("airops", "0061_auto_20210914_2134"),
    ]

    operations = [
        migrations.RunPython(
            populate_waypoint_types, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_threat_types, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_support_types, reverse_code=migrations.RunPython.noop
        ),
    ]
