# Generated by Django 3.2.6 on 2021-09-15 10:31

from django.db import migrations


def move_support_type_to_temp_field(apps, schema_editor):
    model = apps.get_model('airops', 'Support')
    for row in model.objects.all():
        row.temp_type = row.support_type
        row.support_type = None
        row.save(update_fields=['temp_type', 'support_type'])


def move_threat_type_to_temp_field(apps, schema_editor):
    model = apps.get_model('airops', 'Threat')
    for row in model.objects.all():
        row.temp_type = row.threat_type
        row.threat_type = None
        row.save(update_fields=['temp_type', 'threat_type'])


def move_waypoint_type_to_temp_field(apps, schema_editor):
    model = apps.get_model('airops', 'Waypoint')
    for row in model.objects.all():
        row.temp_type = row.waypoint_type
        row.waypoint_type = None
        row.save(update_fields=['temp_type', 'waypoint_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0063_create_temp_fields'),
    ]

    operations = [
        migrations.RunPython(move_support_type_to_temp_field, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(move_threat_type_to_temp_field, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(move_waypoint_type_to_temp_field, reverse_code=migrations.RunPython.noop),
    ]
