# Generated by Django 3.2.6 on 2021-09-15 10:39

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0064_populate_temp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='support_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airops.supporttype'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='threat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airops.threattype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='assets/img/avatars/pilot1.png', force_format='PNG', help_text='User profile image file.', keep_meta=True, quality=0, size=[200, 200], upload_to='user/profile_images/', verbose_name='User profile image.'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='waypoint_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airops.waypointtype'),
        ),
    ]
