# Generated by Django 3.2.6 on 2021-09-15 10:40
from django.db import migrations, models


def move_temp_field_to_support_type(apps, schema_editor):
    model = apps.get_model('airops', 'Support')
    types = apps.get_model('airops', 'SupportType')
    for row in model.objects.all():
        row.support_type = types.objects.get(name=row.temp_type)
        row.save(update_fields=['support_type'])


def move_temp_field_to_threat_type(apps, schema_editor):
    model = apps.get_model('airops', 'Threat')
    types = apps.get_model('airops', 'ThreatType')
    for row in model.objects.all():
        row.threat_type = types.objects.get(name=row.temp_type)
        row.save(update_fields=['threat_type'])


def move_temp_field_to_waypoint_type(apps, schema_editor):
    model = apps.get_model('airops', 'Waypoint')
    types = apps.get_model('airops', 'WaypointType')
    for row in model.objects.all():
        row.waypoint_type = types.objects.get(name=row.temp_type)
        row.save(update_fields=['waypoint_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0065_Switch_To_related_table'),
    ]

    operations = [
        migrations.RunPython(move_temp_field_to_support_type, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(move_temp_field_to_threat_type, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(move_temp_field_to_waypoint_type, reverse_code=migrations.RunPython.noop),
    ]
