# Generated by Django 3.2.6 on 2021-09-16 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airops', '0068_auto_20210916_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='airframe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='airframe',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='airframe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
