# Generated by Django 3.2.6 on 2021-09-16 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0069_auto_20210916_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airframe',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
