# Generated by Django 3.2.13 on 2022-05-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0070_alter_airframe_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='airframe',
            name='dcs_mapping',
            field=models.CharField(choices=[('Not Mapped', 'Not Mapped'), ('Tornado GR4', 'Tornado Gr4'), ('Tornado IDS', 'Tornado Ids'), ('F/A-18A', 'Fa 18A'), ('F/A-18C', 'Fa 18C'), ('F-14A', 'F 14A'), ('Tu-22M3', 'Tu 22M3'), ('F-4E', 'F 4E'), ('B-52H', 'B 52H'), ('MiG-27K', 'Mig 27K'), ('Su-27', 'Su 27'), ('MiG-23MLD', 'Mig 23Mld'), ('Su-25', 'Su 25'), ('Su-25TM', 'Su 25Tm'), ('Su-25T', 'Su 25T'), ('Su-33', 'Su 33'), ('MiG-25PD', 'Mig 25Pd'), ('MiG-25RBT', 'Mig 25Rbt'), ('Su-30', 'Su 30'), ('Su-17M4', 'Su 17M4'), ('MiG-31', 'Mig 31'), ('Tu-95MS', 'Tu 95Ms'), ('Su-24M', 'Su 24M'), ('Su-24MR', 'Su 24Mr'), ('Tu-160', 'Tu 160'), ('F-117A', 'F 117A'), ('B-1B', 'B 1B'), ('S-3B', 'S 3B'), ('S-3B Tanker', 'S 3B Tanker'), ('Mirage 2000-5', 'Mirage 2000 5'), ('F-15C', 'F 15C'), ('F-15E', 'F 15E'), ('MiG-29A', 'Mig 29A'), ('MiG-29G', 'Mig 29G'), ('MiG-29S', 'Mig 29S'), ('Tu-142', 'Tu 142'), ('C-130', 'C 130'), ('An-26B', 'An 26B'), ('An-30M', 'An 30M'), ('C-17A', 'C 17A'), ('A-50', 'A 50'), ('E-3A', 'E 3A'), ('IL-78M', 'Il 78M'), ('E-2C', 'E 2C'), ('IL-76MD', 'Il 76Md'), ('F-16C bl.50', 'F 16C Bl 50'), ('F-16C bl.52d', 'F 16C Bl 52D'), ('F-16A', 'F 16A'), ('F-16A MLU', 'F 16A Mlu'), ('RQ-1A Predator', 'Rq 1A Predator'), ('Yak-40', 'Yak 40'), ('KC-135', 'Kc 135'), ('FW-190D9', 'Fw 190D9'), ('FW-190A8', 'Fw 190A8'), ('Bf-109K-4', 'Bf 109K 4'), ('SpitfireLFMkIX', 'Spitfirelfmkix'), ('SpitfireLFMkIXCW', 'Spitfirelfmkixcw'), ('P-51D', 'P 51D'), ('P-51D-30-NA', 'P 51D 30 Na'), ('P-47D-30', 'P 47D 30'), ('P-47D-30bl1', 'P 47D 30Bl1'), ('P-47D-40', 'P 47D 40'), ('MosquitoFBMkVI', 'Mosquitofbmkvi'), ('A-20G', 'A 20G'), ('A-10A', 'A 10A'), ('A-10C', 'A 10C'), ('A-10C_2', 'A 10C 2'), ('AJS37', 'Ajs37'), ('AV8BNA', 'Av8Bna'), ('KC130', 'Kc130'), ('KC135MPRS', 'Kc135Mprs'), ('C-101EB', 'C 101Eb'), ('C-101CC', 'C 101Cc'), ('J-11A', 'J 11A'), ('JF-17', 'Jf 17'), ('KJ-2000', 'Kj 2000'), ('WingLoong-I', 'Wingloong I'), ('H-6J', 'H 6J'), ('Christen Eagle II', 'Christen Eagle Ii'), ('F-16C_50', 'F 16C 50'), ('F-5E', 'F 5E'), ('F-5E-3', 'F 5E 3'), ('F-86F Sabre', 'F 86F Sabre'), ('F-14B', 'F 14B'), ('F-14A-135-GR', 'F 14A 135 Gr'), ('FA-18C_hornet', 'Fa 18C Hornet'), ('Hawk', 'Hawk'), ('I-16', 'I 16'), ('L-39C', 'L 39C'), ('L-39ZA', 'L 39Za'), ('M-2000C', 'M 2000C'), ('MQ-9 Reaper', 'Mq 9 Reaper'), ('MiG-15bis', 'Mig 15Bis'), ('MiG-19P', 'Mig 19P'), ('MiG-21Bis', 'Mig 21Bis'), ('Su-34', 'Su 34'), ('Yak-52', 'Yak 52'), ('B-17G', 'B 17G'), ('Ju-88A4', 'Ju 88A4'), ('C-47', 'C 47'), ('TF-51D', 'Tf 51D'), ('Ka-50', 'Ka 50'), ('Mi-24V', 'Mi 24V'), ('Mi-8MT', 'Mi 8Mt'), ('Mi-26', 'Mi 26'), ('Ka-27', 'Ka 27'), ('UH-60A', 'Uh 60A'), ('CH-53E', 'Ch 53E'), ('CH-47D', 'Ch 47D'), ('SH-3W', 'Sh 3W'), ('AH-64A', 'Ah 64A'), ('AH-64D', 'Ah 64D'), ('AH-1W', 'Ah 1W'), ('SH-60B', 'Sh 60B'), ('UH-1H', 'Uh 1H'), ('Mi-28N', 'Mi 28N'), ('OH-58D', 'Oh 58D'), ('AH-64D_BLK_II', 'Ah 64D Blk Ii'), ('Mi-24P', 'Mi 24P'), ('SA342M', 'Sa342M'), ('SA342L', 'Sa342L'), ('SA342Mistral', 'Sa342Mistral'), ('SA342Minigun', 'Sa342Minigun')], default='Not Mapped', max_length=50),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='airframe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='combatflitefile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flightimagery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missionfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missionimagery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packageimagery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='squadron',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='support',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supporttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threattype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waypointtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
