# Generated by Django 3.2.6 on 2022-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0070_alter_airframe_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='discord_api_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Discord API Event ID'),
        ),
    ]
