# Generated by Django 3.2.13 on 2022-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0071_auto_20220519_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypointtype',
            name='dcs_mapping',
            field=models.CharField(choices=[('Not Mapped', 'Not Mapped'), ('TakeOffParking', 'Takeoffparking'), ('TakeOffParkingHot', 'Takeoffparkinghot'), ('Turning Point', 'Turning Point')], default='Not Mapped', max_length=50),
        ),
    ]
