# Generated by Django 4.2.3 on 2023-10-13 05:01

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0071_mission_discord_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='aoImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='An image of the Area of Operations.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/ao_images', verbose_name='area of Operations Image'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Campaign Image File.', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='campaign/thumbnails/', verbose_name='Campaign Image Thumbnail.'),
        ),
        migrations.AlterField(
            model_name='flightimagery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for flight.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/flight_images/', verbose_name='Flight Imagery'),
        ),
        migrations.AlterField(
            model_name='missionfile',
            name='file_type',
            field=models.CharField(choices=[('MIZ', 'Mission'), ('LIB', 'Liberation'), ('COM', 'CombatFlite'), ('TAC', 'Tacview'), ('OTH', 'Other')], default='MIZ', max_length=10),
        ),
        migrations.AlterField(
            model_name='missionimagery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for mission.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/mission_images/', verbose_name='Mission Imagery'),
        ),
        migrations.AlterField(
            model_name='packageimagery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for package.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/package_images/', verbose_name='Package Imagery'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image of the target.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/target_images/', verbose_name='Target Image'),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='rwr_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier'),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='rwr_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier'),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='rwr_image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='assets/img/avatars/pilot1.png', force_format='PNG', help_text='User profile image file.', keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='user/profile_images/', verbose_name='User profile image.'),
        ),
        migrations.CreateModel(
            name='AirframeDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(help_text='Call sign for this type of airframe.', max_length=20)),
                ('default_radio_freq', models.CharField(help_text='Default radio frequency.', max_length=8)),
                ('laser_code', models.CharField(help_text='Default laser code.', max_length=8)),
                ('airframe_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.airframe')),
            ],
            options={
                'verbose_name': 'Airframe Defaults',
                'verbose_name_plural': 'Airframe Defaults',
                'ordering': ['-airframe_type', '-callsign'],
            },
        ),
    ]
