# Generated by Django 4.2.3 on 2023-10-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0072_alter_campaign_aoimage_alter_campaign_campaignimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airframedefaults',
            name='default_radio_freq',
            field=models.CharField(help_text='Default radio frequency.', max_length=15),
        ),
        migrations.AlterField(
            model_name='airframedefaults',
            name='laser_code',
            field=models.CharField(help_text='Default laser code.', max_length=10),
        ),
    ]
