# Generated by Django 3.2.13 on 2022-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0072_waypointtype_dcs_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airframe',
            name='dcs_mapping',
            field=models.CharField(choices=[('Not Mapped', 'Not Mapped'), ('A-10A', 'A 10A'), ('A-10C', 'A 10C'), ('A-10C_2', 'A 10C 2'), ('A-20G', 'A 20G'), ('A-50', 'A 50'), ('AJS37', 'Ajs37'), ('AV8BNA', 'Av8Bna'), ('An-26B', 'An 26B'), ('An-30M', 'An 30M'), ('B-17G', 'B 17G'), ('B-1B', 'B 1B'), ('B-52H', 'B 52H'), ('Bf-109K-4', 'Bf 109K 4'), ('C-101CC', 'C 101Cc'), ('C-101EB', 'C 101Eb'), ('C-130', 'C 130'), ('C-17A', 'C 17A'), ('C-47', 'C 47'), ('Christen Eagle II', 'Christen Eagle Ii'), ('E-2C', 'E 2C'), ('E-3A', 'E 3A'), ('F-117A', 'F 117A'), ('F-14A', 'F 14A'), ('F-14A-135-GR', 'F 14A 135 Gr'), ('F-14B', 'F 14B'), ('F-15C', 'F 15C'), ('F-15E', 'F 15E'), ('F-16A', 'F 16A'), ('F-16A MLU', 'F 16A Mlu'), ('F-16C bl.50', 'F 16C Bl 50'), ('F-16C bl.52d', 'F 16C Bl 52D'), ('F-16C_50', 'F 16C 50'), ('F-4E', 'F 4E'), ('F-5E', 'F 5E'), ('F-5E-3', 'F 5E 3'), ('F-86F Sabre', 'F 86F Sabre'), ('F/A-18A', 'Fa 18A'), ('F/A-18C', 'Fa 18C'), ('FA-18C_hornet', 'Fa 18C Hornet'), ('FW-190A8', 'Fw 190A8'), ('FW-190D9', 'Fw 190D9'), ('H-6J', 'H 6J'), ('Hawk', 'Hawk'), ('I-16', 'I 16'), ('IL-76MD', 'Il 76Md'), ('IL-78M', 'Il 78M'), ('J-11A', 'J 11A'), ('JF-17', 'Jf 17'), ('Ju-88A4', 'Ju 88A4'), ('KC-135', 'Kc 135'), ('KC130', 'Kc130'), ('KC135MPRS', 'Kc135Mprs'), ('KJ-2000', 'Kj 2000'), ('L-39C', 'L 39C'), ('L-39ZA', 'L 39Za'), ('M-2000C', 'M 2000C'), ('MQ-9 Reaper', 'Mq 9 Reaper'), ('MiG-15bis', 'Mig 15Bis'), ('MiG-19P', 'Mig 19P'), ('MiG-21Bis', 'Mig 21Bis'), ('MiG-23MLD', 'Mig 23Mld'), ('MiG-25PD', 'Mig 25Pd'), ('MiG-25RBT', 'Mig 25Rbt'), ('MiG-27K', 'Mig 27K'), ('MiG-29A', 'Mig 29A'), ('MiG-29G', 'Mig 29G'), ('MiG-29S', 'Mig 29S'), ('MiG-31', 'Mig 31'), ('Mirage 2000-5', 'Mirage 2000 5'), ('MosquitoFBMkVI', 'Mosquitofbmkvi'), ('P-47D-30', 'P 47D 30'), ('P-47D-30bl1', 'P 47D 30Bl1'), ('P-47D-40', 'P 47D 40'), ('P-51D', 'P 51D'), ('P-51D-30-NA', 'P 51D 30 Na'), ('RQ-1A Predator', 'Rq 1A Predator'), ('S-3B', 'S 3B'), ('S-3B Tanker', 'S 3B Tanker'), ('SpitfireLFMkIX', 'Spitfirelfmkix'), ('SpitfireLFMkIXCW', 'Spitfirelfmkixcw'), ('Su-17M4', 'Su 17M4'), ('Su-24M', 'Su 24M'), ('Su-24MR', 'Su 24Mr'), ('Su-25', 'Su 25'), ('Su-25T', 'Su 25T'), ('Su-25TM', 'Su 25Tm'), ('Su-27', 'Su 27'), ('Su-30', 'Su 30'), ('Su-33', 'Su 33'), ('Su-34', 'Su 34'), ('TF-51D', 'Tf 51D'), ('Tornado GR4', 'Tornado Gr4'), ('Tornado IDS', 'Tornado Ids'), ('Tu-142', 'Tu 142'), ('Tu-160', 'Tu 160'), ('Tu-22M3', 'Tu 22M3'), ('Tu-95MS', 'Tu 95Ms'), ('WingLoong-I', 'Wingloong I'), ('Yak-40', 'Yak 40'), ('Yak-52', 'Yak 52'), ('AH-1W', 'Ah 1W'), ('AH-64A', 'Ah 64A'), ('AH-64D', 'Ah 64D'), ('AH-64D_BLK_II', 'Ah 64D Blk Ii'), ('CH-47D', 'Ch 47D'), ('CH-53E', 'Ch 53E'), ('Ka-27', 'Ka 27'), ('Ka-50', 'Ka 50'), ('Mi-24P', 'Mi 24P'), ('Mi-24V', 'Mi 24V'), ('Mi-26', 'Mi 26'), ('Mi-28N', 'Mi 28N'), ('Mi-8MT', 'Mi 8Mt'), ('OH-58D', 'Oh 58D'), ('SA342L', 'Sa342L'), ('SA342M', 'Sa342M'), ('SA342Minigun', 'Sa342Minigun'), ('SA342Mistral', 'Sa342Mistral'), ('SH-3W', 'Sh 3W'), ('SH-60B', 'Sh 60B'), ('UH-1H', 'Uh 1H'), ('UH-60A', 'Uh 60A')], default='Not Mapped', max_length=50),
        ),
    ]
