# Generated by Django 3.2.15 on 2022-08-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0071_mission_discord_api_id'),
        ('airops', '0073_alter_airframe_dcs_mapping'),
    ]

    operations = [
    ]
