# Generated by Django 4.2.3 on 2023-10-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airops', '0074_airframedefaults_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airframe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airops.airframe'),
        ),
    ]
